- hosts: all
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true
    
    - name: start Docker
      service:
        name: docker
        state: started
        enabled: true
    
    - name: Install APT Transport HTTPS
      apt:
        name: apt-transport-https
        state: present

    - name: add kubernetes apt-key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: add kubernetes apt repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: 'kubernetes.list'
        
    - name: install kubectl
      apt:
        name: kubectl=1.19.0-00
        state: present
        force: yes
    
    - name: install kubelet
      apt:
        name: kubelet=1.19.0-00
        state: present
        force: yes
        update_cache: true
    
    - name: install kubeadm
      apt:
        name: kubeadm=1.19.0-00
        state: present
        force: yes
    
    - name: Start kubelet
      service:
        name: kubelet
        state: restarted
        enabled: true
    

